version: '3.8'
services:
  webapp_proxmox:
    image: python:3.13.1-bookworm
    command: /bin/bash -c 'wget https://raw.githubusercontent.com/Daniel-Tomov/Cloud/refs/heads/main/proxmox/run.sh ; sh run.sh'
    ports:
     - 5556:5556
    volumes:
     - ../../vm-options.yaml:/usr/src/vm-options.yaml

    