apiVersion: v1
kind: Service
metadata:
metadata:
  name: proxmox-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 32001
    protocol: TCP
    targetPort: 5556
    nodePort: 32001
  selector:
    app: proxmox
  sessionAffinity: None