
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-prune
  labels:
    app: db-prune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-prune
  template:
    metadata:
      labels:
        app: db-prune
    spec:
      containers:
        - image: python:3.13.1-bookworm
          name: db-prune
          imagePullPolicy: Always
          args:
            - /bin/bash
            - -c
            - "wget https://raw.githubusercontent.com/Daniel-Tomov/Cloud/refs/heads/main/postgres/run.sh; chmod +x run.sh ; ./run.sh"
          
          volumeMounts:
            - name: vm-options-volume
              mountPath: /usr/src/Cloud
              subPath: vm-options.yaml
      volumes:
        - name: vm-options-volume
          configMap:
            name: env

      restartPolicy: Always
