version: '3.8'
services:
  webapp_db:
    image: python:3.13.1-bookworm
    command: /bin/bash -c 'wget https://raw.githubusercontent.com/Daniel-Tomov/Cloud/refs/heads/main/postgres/run.sh ; sh run.sh'
    ports:
     - 5557:5557
    volumes:
     - ../vm-options.yaml:/usr/src/vm-options.yaml

    