apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 32000
    targetPort: 5555
    nodePort: 32000
  selector:
    app: webapp
  sessionAffinity: None
